# -*- coding: utf-8 -*-
"""bonus_assignment_b19cse114_b19cse053.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MaU3nKON8Xk9D5tMgeCeE5k1oTEpR0up
"""

import cv2
import numpy as np
import pandas as pd
import os 
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator 
import matplotlib.pyplot as plt
import seaborn as sns

# from zipfile import ZipFile
# file_name = '/content/masked.zip'

# with ZipFile(file_name, 'r') as zip:
#   zip.extractall()
#   print('Done')

# from zipfile import ZipFile
# file_name1 = '/content/nomasked_5000images.zip'

# with ZipFile(file_name1, 'r') as zip:
#   zip.extractall()
#   print('Done')

masked = '/content/masked/'
nomasked = '/content/nomasked_5000images/'
print(len(os.listdir(masked)))
print(len(os.listdir(nomasked)))

masked_label = [1 for i in range(805)]
nomasked_label = [0 for i in range(5000)]

a = os.listdir(masked)
a[:5]

b = os.listdir(nomasked)
b[:5]

img = image.load_img(masked+f'{a[0]}')
plt.imshow(img)

img1 = image.load_img(nomasked+f'{b[0]}')
plt.imshow(img1)

cv2.imread(masked+f'{a[0]}').shape

from PIL import Image

imge = Image.open(masked+f'{a[0]}')
imge.size

# resize_img = imge.resize((32,32))
# a = cv2.imread(resize_img)
# a

def image_processing(images_path,type1):
  image_ = []
  resize_ = []
  for i in os.listdir(images_path):
    imge = Image.open(images_path+f'{i}')
    image_.append(imge)
  for images in image_:
    resize_img = images.resize((64,64))
    resize_.append(resize_img)
  if (type1 == 'masked'):
    for i, new in enumerate(resize_):
      new.save(f'/content/masked_resizeimg1/{i+1}.png')
  if (type1 == 'nomasked'):
    for i, new in enumerate(resize_):
      new.save(f'/content/nomasked_resize1/{i+1}.png')
  return resize_

# resized_images_1 = image_processing(masked,'masked')

# resized_images_2 = image_processing(nomasked,'nomasked')

newmasked = '/content/masked_resizeimg1/'
newnomasked = '/content/nomasked_resize1/'
print(len(os.listdir(newmasked)))
print(len(os.listdir(newnomasked)))

a1 = os.listdir(newmasked)
a2 = os.listdir(newnomasked)
a1

image__ = cv2.imread(newmasked+f'{a1[10]}')#10,2,3
plt.imshow(image__)

data = []
for i in a1:
  read_img = cv2.imread(newmasked+f'{i}')
  data.append(read_img)
for i in a2:
  read_img1 = cv2.imread(newnomasked+f'{i}')
  data.append(read_img1)
data = np.array(data)

data.shape

data = data.reshape(data.shape[0] ,data.shape[1]*data.shape[2]*data.shape[3])
data.shape

dataframe = pd.DataFrame(columns = [f'f{i}' for i in range(data.shape[1])],data = data)
dataframe.shape

dataframe.head()

plt.imshow(np.array(dataframe.iloc[0,:]).reshape(64,64,3))

dataframe['labels'] = masked_label+nomasked_label

dataframe.to_csv('/content/data.csv',index=False)





# to be deleted 
newmasked1 = '/content/masked_resizeimg/'
newnomasked1 = '/content/nomasked_resize/'
print(len(os.listdir(newmasked1)))
print(len(os.listdir(newnomasked1)))

a1 = os.listdir(newmasked1)
a2 = os.listdir(newnomasked1)

data = []
for i in a1:
  read_img = cv2.imread(newmasked1+f'{i}')
  data.append(read_img)
for i in a2:
  read_img1 = cv2.imread(newnomasked1+f'{i}')
  data.append(read_img1)
data = np.array(data)

data.shape

data = data.reshape(data.shape[0] ,data.shape[1]*data.shape[2]*data.shape[3])
data.shape

dataframe = pd.DataFrame(columns = [f'f{i}' for i in range(data.shape[1])],data = data)
dataframe.shape

dataframe['labels'] = masked_label+nomasked_label

dataframe.to_csv('/content/data_32.csv',index=False)

